name: CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      # Ensure the script has executable permissions
      - name: Make build script executable
        run: chmod +x unleash/scripts/build-frontend-if-needed.sh

      # Run the build script
      - name: Run yarn build:frontend:if-needed
        run: unleash/scripts/build-frontend-if-needed.sh

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/**

      # Run Unit Test
      - name: Run Unit Test
        run: ./gradlew test

      # Upload Test Reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/**

      # Generate Code Coverage Report
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      # Upload Code Coverage Report
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/**

      # Run Deployment
      - name: Run Deployment
        run: java -jar build/libs/unleash-test-V1.jar
